model_name: roberta-large
max_len_prompt: 256
max_len_resp: 250
lr: 2e-5
batch_size: 4
num_epochs: 3
weight_decay: 0.01
warmup_ratio: 0.06
seed: 42
use_ordinal_tie: true
num_workers: 6
amp: true
grad_accum: 1
